### ISSUE TITLE
Releases in GitHub

### ISSUE THREAD

**Issue by djmitche** [erdtman/content-security-policy#4]
Hi there!

The JS world has had lots of attacks via libraries that were taken over by someone malicious.  A best practice is to check changes before upgrading, and trace those back to the relevant GitHub repository.  It's not foolproof, but helps.

https://github.com/taskcluster/taskcluster/pull/3390 is an example of an upgrade request for this package, but notably its changelog link doesn't point to anything useful, and I don't see a 3.0.4 commit, tag, or release here -- so I'm reluctant to adopt the upgrade.

Could you push the 3.0.4 change, and perhaps also add tags and releases in GitHub?  It *looks* like this was just a compatibility bump, but seeing all those pieces in place would help be sure of that.

**Comment by erdtman** [comment]
That is a good point, I´ll see what I can do. (I do not do these things every day so I might have to ask you for some guidence to get it right)

**Comment by djmitche** [comment]
I'm happy to help :)

**Comment by erdtman** [comment]
Just pushed tags and created a release for the latest tag. does it look good to you?

and yes the releas was just to update dependencies and parameters to the travis build env. And the dependencies was dev dependencis so I´m not sure if that affects your setup.

**Comment by djmitche** [comment]
That looks great -- thanks!!

**Comment by djmitche** [comment]
..and shows up nicely in Renovate PRs:

![image](https://user-images.githubusercontent.com/28673/90342503-cdfb1100-dfd6-11ea-9ea9-3bd0bfd6c448.png)

**Comment by erdtman** [comment]
Awesome thank you, you have thought me something new. Now I will apply this new found knowledge to my other libraries.
